import fnmatch
import os

#opts = Options('SCustomize')
#opts.Add('debug', 'Build with debugging symbols', 0)
opt = Variables()
opt.Add('debug', help='Build with debugging symbols', default=0)
#opt.AddVariables(
#        ('debug', '', 0),
#        )

matches = []
for root, dirnames, filenames in os.walk('.'):
    for filename in fnmatch.filter(filenames, '*.c'):
        matches.append(os.path.join(root, filename))
#Add the main c files too
for root, dirnames, filenames in os.walk('../src'):
    for filename in fnmatch.filter(filenames, '*.c'):
        if(filename != "main.c"):
            matches.append(os.path.join(root, filename))


#env = Environment(CPPPATH = ['.', '../lib/external/arch64/include/chipmunk'], CFLAGS='-g -Werror -std=c99 -L ../lib/external/arch64/lib')
#env = Environment(variables=opt, CPPPATH = ['.', '../lib/external/arch64/include/chipmunk'], CFLAGS=['-std=c99', '-L ../lib/external/arch64/lib'])
env = Environment(variables=opt, CPPPATH = ['.', '../src'], CFLAGS=['-std=c99'])

env.ParseConfig('sdl-config --cflags')
env.ParseConfig('sdl-config --libs')
env.ParseConfig('freealut-config --cflags')
env.ParseConfig('freealut-config --libs')
env.ParseConfig('pkg-config --cflags glib-2.0')
env.ParseConfig('pkg-config --libs glib-2.0')

debug = env.get('debug',1)

if debug=='1':
    env.Append(CFLAGS = ['-g', '-Werror'])
else:
    env.Append(CFLAGS = ['-O3'])

env.Append(LIBS = ['check', 'GL', 'SDL_image', 'm', File('../lib/external/arch64/lib/libchipmunk.a')])

env.Program('pmujtest', matches)
