#ifndef  NXCONSTANTS_H
#define  NXCONSTANTS_H

#define NX_MAX_ENTITIES 1024

#define NX_SCREEN_WIDTH 800
#define NX_SCREEN_HEIGHT 600
#define NX_SCREEN_BPP 32

#define NX_PADDLE_HALFWIDTH 50.0f
#define NX_PADDLE_HALFHEIGHT 25.0f

#define NX_BALL_HALFWIDTH 15.0f
#define NX_BALL_HALFHEIGHT 15.0f

#define NX_PLAYER_HALFWIDTH 25.0f
#define NX_PLAYER_HALFHEIGHT 25.0f


#endif   // NXCONSTANTS_H
