import fnmatch
import os

matches = []
for root, dirnames, filenames in os.walk('.'):
  for filename in fnmatch.filter(filenames, '*.c'):
      matches.append(os.path.join(root, filename))


env = Environment(CPPPATH = ['.'], CFLAGS='-Werror -std=c99')

env.ParseConfig('sdl-config --cflags')
env.ParseConfig('sdl-config --libs')
env.Append(LIBS = ['GL'])

env.Program('pmuj', matches)
