import fnmatch
import os

matches = []
for root, dirnames, filenames in os.walk('.'):
  for filename in fnmatch.filter(filenames, '*.c'):
      matches.append(os.path.join(root, filename))


env = Environment(CPPPATH = ['.', '../lib/external/arch64/include/chipmunk'], CFLAGS='-Werror -std=c99 -L ../lib/external/arch64/lib')

env.ParseConfig('sdl-config --cflags')
env.ParseConfig('sdl-config --libs')
env.Append(LIBS = ['GL', 'm', 'chipmunk'])

env.Program('pmuj', matches)
